---
- name: install web components
  apt: name={{item}} state=present
  with_items: 
    - python-pip
    - python-virtualenv
    - python-mysqldb
  tags: ['packages']

- name: copy demo app source
  # slash at the end of app/ means to copy the contents of directory and not the directory itself
  copy: src=demo/app/ dest=/var/www/demo mode=0755
  # notify will be invoked only once even if multiple same handler notifications will be called
  notify: restart apache2
  tags: ['configure']

- name: copy demo.wsgi conf
  # demo.wsgi is now a template and should be put rendered
  # template looks in role/templates folder by default
  template: src=demo.wsgi.j2 dest=/var/www/demo/demo.wsgi mode=0755
  notify: restart apache2
  tags: ['configure']

- name: copy apache virtual host config
  copy: src=demo/demo.conf dest=/etc/apache2/sites-available mode=0755
  notify: restart apache2
  tags: ['configure']

- name: setup python virtualenv
  pip:  requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
  notify: restart apache2
  tags: ['system']

- name: deactivate default apache site
  # modifying files on the guest system
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2
  tags: ['configure']