---
- name: install tools
  apt:  name={{item}} state=present
  with_items:
    - python-httplib2
  tags: ['packages']
    
- name: install nginx
  # become: true
  apt:  name=nginx  state=present
  tags: ['packages']

- name: Configure nginx sites
  # template path should be relative to role/templates directory  
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/{{item.key}} mode=0644
  with_dict: '{{sites}}'
  notify: restart nginx
  tags: ['configure']

- name: get-active sites
  shell: ls -1 /etc/nginx/sites-enabled
  register: active
  # sites is a var from default section
  changed_when: "active.stdout_lines != sites.keys()"
  tags: ['configure']

- name: deactivate sites
  file: path=/etc/nginx/sites-enabled/{{item}} state=absent
  with_items: '{{active.stdout_lines}}'
  when: item not in sites
  notify: restart nginx
  tags: ['configure']

- name: Activate demo sites
  file: src=/etc/nginx/sites-available/{{item.key}} dest=/etc/nginx/sites-enabled/{{item.key}} state=link
  with_dict: '{{sites}}'  
  notify: restart nginx
  tags: ['configure']

- name: ensure nginx is running
  service:  name=nginx state=started enabled=yes
  tags: ['service']
