---
- name: install web components
  apt: name={{item}} state=present update_cache=yes
  with_items: 
    - apache2
    - libapache2-mod-wsgi

- name: ensure mod_wsgi is enabled
  apache2_module: state=present name=wsgi
  # notify will fire up handler with this name 
  notify: restart apache2


- name: activate demo site
  file: src=/etc/apache2/sites-available/demo.conf dest=/etc/apache2/sites-enabled/demo.conf state=link
  notify: restart apache2
  
- name: ensure apache2 is running
  service:  name=apache2 state=started enabled=yes

